### ISSUE TITLE
Soft Reset should not unmount virtual .d64 file on SD card

### ISSUE THREAD

**Issue by Kugelblitz360** [MJoergen/C64MEGA65#156] opened 2024-09-04 11:36 UTC
Currently any kind of reset (either M65 button or cartridge Reset button) does unmount the currently mounted .d64 file.

The filebrowser does remember the current directory, but if there are many disk-images in there, it is a pain to re-mount.

The standard behaviour should be to keep the disk mounted - as a 1541 will also not eject its disk when the C64 resets.

We might also want to add an option to select a .d64 that automatically should be mounted after a reset, name/path stored in the config file.

**Comment by sy2002** [comment] 2024-09-06 17:06
Thank you @Kugelblitz360 - this makes sense, we will make this configurable (same as in MiSTer). This issue is a duplicate of issue https://github.com/MJoergen/C64MEGA65/issues/81 and therefore I am closing it, we will continue to track this in issue https://github.com/MJoergen/C64MEGA65/issues/81.

**Closed by sy2002** 2024-09-06 17:06 UTC
